version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: csgoskins_postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: csgoskinsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: